version: '3.11'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    #    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app/.env
volumes:
  postgres_data: